#%RAML 1.0 NamedExample
patchOrderResponse:
    {
    "status" : "order updated successfully",
    "data" :{
      "orderNumber": "00000102",
  "AccountId": "9999",
  "TotalAmount": "101",
  "EffectiveDate": "9/23/2021",
  "status": "Draft",
  "userId": "100"
}
}